### ISSUE TITLE
would love to see a screen recording of shiba in action

### ISSUE THREAD

**Issue by freder** [KoltesDigital/shiba#1]
hi,

I wanted to send you an email about this, but the link on your website seems to be broken. feel free to delete this "issue".
shiba sounds interesting, and I'd like to know more about it, so I wanted to ask if there is a screen recording of how the tool is being used, by any chance.

f

**Comment by KoltesDigital** [comment]
Hi,

Thanks for keeping up contacting me! Sadly right now I don't have time to work on Shiba nor on my website. I thought I could!

You can see some screen recordings on [Leon's Twitter account](https://twitter.com/leondenise), e.g. https://twitter.com/leondenise/status/1213506905009795073 or https://twitter.com/leondenise/status/1197851188043096064. It's actually what you would have if you download the repos, but documentation is scarce.

I still don't advertise this project much because it lacks an important feature for me: being able to export animations from Blender to the executable. After that, I'll make some introduction videos.

**Comment by freder** [comment]
great, thank you!
looking forward to seeing more in the future. 👍
